In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('./csi_data.csv')

In [5]:
data.head()

,id,time,amplitude1_1,amplitude2_1,amplitude3_1,amplitude4_1,amplitude5_1,amplitude6_1,amplitude7_1,amplitude8_1,...,phase58_2,phase59_2,phase60_2,phase61_2,phase62_2,phase63_2,phase64_2,rssi_1,rssi_2,activity
0,0,16:14:40,115.277925,4,33.060551,28.071338,22.000000,17.117243,13.000000,13.453624,...,-1.735945,-1.789465,-1.866237,-2.034444,-2.356194,-2.819842,3.141593,-52,-54,0
1,1,16:14:40,115.277925,4,34.438351,29.068884,22.825424,17.204651,13.601471,13.341664,...,2.896614,2.867425,2.754717,2.601173,2.245537,1.789465,1.480136,-52,-54,0
2,2,16:14:40,115.277925,4,34.205263,29.068884,23.600847,18.357560,15.524175,14.035669,...,1.180189,1.134169,1.042722,0.909753,0.643501,0.197396,-0.099669,-52,-55,0
3,3,16:14:40,115.277925,4,30.000000,25.019992,21.000000,16.124516,13.000000,12.041595,...,-2.828691,-2.859038,-2.958482,3.141593,2.819842,2.319174,2.034444,-53,-54,0
4,4,16:14:40,115.277925,4,31.780497,27.313001,21.540659,16.492423,14.000000,13.000000,...,0.000000,-0.034469,-0.119429,-0.352990,-0.702257,-1.158386,-1.471128,-53,-54,0

In [6]:
groupedData = data.groupby('time')

In [7]:
unique_times = data['time'].unique()

In [8]:
unique_times

array(['16:14:40', '16:14:41', '16:14:42', ..., '19:24:01', '19:24:02',
       '19:24:03'], dtype=object)

In [9]:
groupedData

In [10]:
groupedDataSizes = groupedData.size()

In [11]:
len(groupedData)

4342

In [12]:
len(groupedDataSizes)

4342

In [13]:
canGetCount = 0
cannotGetCount = 0

In [14]:
newDataFrame = pd.DataFrame(columns=data.columns)

In [18]:
for i in range(len(groupedData)):
  count = groupedDataSizes[i]
  if count > 24:
    group = groupedData.get_group(unique_times[i])
    factor = count / 25
    for j in range(25):
      rowIndex = int(j * factor)
      newDataFrame = pd.concat([newDataFrame, group.iloc[rowIndex]], ignore_index=True)

  else:
    cannotGetCount += 1

C:\Users\yasir\AppData\Local\Temp\ipykernel_22872\383899212.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count = groupedDataSizes[i]
C:\Users\yasir\AppData\Local\Temp\ipykernel_22872\383899212.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count = groupedDataSizes[i]

In [16]:
newDataFrame.head()

Empty DataFrame
Columns: [id, time, amplitude1_1, amplitude2_1, amplitude3_1, amplitude4_1, amplitude5_1, amplitude6_1, amplitude7_1, amplitude8_1, amplitude9_1, amplitude10_1, amplitude11_1, amplitude12_1, amplitude13_1, amplitude14_1, amplitude15_1, amplitude16_1, amplitude17_1, amplitude18_1, amplitude19_1, amplitude20_1, amplitude21_1, amplitude22_1, amplitude23_1, amplitude24_1, amplitude25_1, amplitude26_1, amplitude27_1, amplitude28_1, amplitude29_1, amplitude30_1, amplitude31_1, amplitude32_1, amplitude33_1, amplitude34_1, amplitude35_1, amplitude36_1, amplitude37_1, amplitude38_1, amplitude39_1, amplitude40_1, amplitude41_1, amplitude42_1, amplitude43_1, amplitude44_1, amplitude45_1, amplitude46_1, amplitude47_1, amplitude48_1, amplitude49_1, amplitude50_1, amplitude51_1, amplitude52_1, amplitude53_1, amplitude54_1, amplitude55_1, amplitude56_1, amplitude57_1, amplitude58_1, amplitude59_1, amplitude60_1_1, amplitude61_1, amplitude62_1, amplitude63_1, amplitude64_1, phase1_1, phase2_1, phase3_1, phase4_1, phase5_1, phase6_1, phase7_1, phase8_1, phase9_1, phase10_1, phase11_1, phase12_1, phase13_1, phase14_1, phase15_1, phase16_1, phase17_1, phase18_1, phase19_1, phase20_1, phase21_1, phase22_1, phase23_1, phase24_1, phase25_1, phase26_1, phase27_1, phase28_1, phase29_1, phase30_1, phase31_1, phase32_1, phase33_1, phase34_1, ...]
Index: []

[0 rows x 261 columns]

In [43]:
print(cannotGetCount)

960