In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('./csi_data.csv')

In [5]:
data.head()

,id,time,amplitude1_1,amplitude2_1,amplitude3_1,amplitude4_1,amplitude5_1,amplitude6_1,amplitude7_1,amplitude8_1,...,phase58_2,phase59_2,phase60_2,phase61_2,phase62_2,phase63_2,phase64_2,rssi_1,rssi_2,activity
0,0,16:14:40,115.277925,4,33.060551,28.071338,22.000000,17.117243,13.000000,13.453624,...,-1.735945,-1.789465,-1.866237,-2.034444,-2.356194,-2.819842,3.141593,-52,-54,0
1,1,16:14:40,115.277925,4,34.438351,29.068884,22.825424,17.204651,13.601471,13.341664,...,2.896614,2.867425,2.754717,2.601173,2.245537,1.789465,1.480136,-52,-54,0
2,2,16:14:40,115.277925,4,34.205263,29.068884,23.600847,18.357560,15.524175,14.035669,...,1.180189,1.134169,1.042722,0.909753,0.643501,0.197396,-0.099669,-52,-55,0
3,3,16:14:40,115.277925,4,30.000000,25.019992,21.000000,16.124516,13.000000,12.041595,...,-2.828691,-2.859038,-2.958482,3.141593,2.819842,2.319174,2.034444,-53,-54,0
4,4,16:14:40,115.277925,4,31.780497,27.313001,21.540659,16.492423,14.000000,13.000000,...,0.000000,-0.034469,-0.119429,-0.352990,-0.702257,-1.158386,-1.471128,-53,-54,0

In [6]:
groupedData = data.groupby('time')

In [7]:
unique_times = data['time'].unique()

In [8]:
unique_times

array(['16:14:40', '16:14:41', '16:14:42', ..., '19:24:01', '19:24:02',
       '19:24:03'], dtype=object)

In [9]:
groupedData

In [10]:
groupedDataSizes = groupedData.size()

In [11]:
len(groupedData)

4342

In [12]:
len(groupedDataSizes)

4342

In [13]:
canGetCount = 0
cannotGetCount = 0

In [14]:
newDataFrame = pd.DataFrame(columns=data.columns)

In [19]:
selectedRows = []

In [20]:
for i in range(len(groupedData)):
  count = groupedDataSizes[i]
  if count > 24:
    group = groupedData.get_group(unique_times[i])
    factor = count / 25
    for j in range(25):
      rowIndex = int(j * factor)
      selectedRows.append(group.iloc[rowIndex])

  else:
    cannotGetCount += 1

C:\Users\yasir\AppData\Local\Temp\ipykernel_22872\3930323679.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  count = groupedDataSizes[i]

In [22]:
newDataFrame = pd.DataFrame(selectedRows)

In [23]:
newDataFrame.head()

,id,time,amplitude1_1,amplitude2_1,amplitude3_1,amplitude4_1,amplitude5_1,amplitude6_1,amplitude7_1,amplitude8_1,...,phase58_2,phase59_2,phase60_2,phase61_2,phase62_2,phase63_2,phase64_2,rssi_1,rssi_2,activity
32,32,16:14:43,115.277925,4,34.000000,29.068884,23.706539,18.867962,14.866069,13.000000,...,-0.617191,-0.661043,-0.761013,-0.927295,-1.279340,-1.719686,-1.997424,-53,-54,0
34,34,16:14:43,115.277925,4,33.955854,28.861739,24.738634,18.973666,15.264338,14.212670,...,-2.096863,-2.142134,-2.234842,-2.356194,-2.634494,-3.036716,2.896614,-53,-53,0
36,36,16:14:43,115.277925,4,32.802439,28.600699,22.803509,18.439089,14.422205,13.341664,...,2.577023,2.510513,2.455863,2.325901,2.010639,1.570796,1.264917,-53,-53,0
38,38,16:14:43,115.277925,4,29.681644,25.238859,21.095023,16.552945,13.341664,12.165525,...,-1.961403,-2.007423,-2.094075,-2.239086,-2.488746,-2.884269,3.046641,-53,-53,0
41,41,16:14:43,115.277925,4,32.280025,26.925824,22.561028,17.117243,13.152946,12.529964,...,0.849141,0.808650,0.732815,0.563316,0.270947,-0.174672,-0.531724,-53,-54,0

In [43]:
print(cannotGetCount)

960